color: null
description: null
fieldLayouts:
  81c96262-5476-4a8c-ba07-09b532e2b4a3:
    cardThumbAlignment: start
    cardView:
      - 'layoutElement:822785e5-b4a3-48f3-b672-76a84be86462'
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-21T11:44:17+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8a24d274-81ff-485b-a833-2bb7f51b19f4 # Image
            handle: null
            includeInCards: true
            instructions: null
            label: null
            providesThumbs: true
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 822785e5-b4a3-48f3-b672-76a84be86462
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 04678055-ec1c-4ea5-9afe-01b223d1a237
        userCondition: null
handle: images_1080x1350
hasTitleField: false
icon: grid
name: 'Matrix Image Grid 1080x1350'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
