color: null
description: null
fieldLayouts:
  050e06c9-a5e2-4bb0-b403-5bdb45c50b57:
    cardThumbAlignment: end
    cardView:
      - 'layoutElement:a317eed7-8977-4590-8ba5-2da70a92d28f'
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-01T08:57:52+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Titel
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9b1853f7-2c46-4a8d-9485-f37e9c61460b
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-08-01T09:01:46+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c1c4a87b-7ed0-4bf8-b09a-8ced23b78cbe # Rich text
            handle: matrixMeedoenActiesText
            includeInCards: true
            instructions: null
            label: Tekst
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a317eed7-8977-4590-8ba5-2da70a92d28f
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: dae5476c-6967-485d-9e31-93c005bf59f1
        userCondition: null
handle: matrixMeedoenActies
hasTitleField: true
icon: bullseye-pointer
name: 'Matrix Meedoen Acties'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
