color: null
description: null
fieldLayouts:
  99a0ec88-8fc9-4a24-9623-0a394d24f580:
    cardThumbAlignment: start
    cardView:
      - 'layoutElement:b0324f09-951f-4082-96e3-c017287099de'
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-01T08:09:05+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: 'Naam bondgenoot'
            label: 'Bondgenoot naam'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0a3fcc36-7cfe-4570-8473-3ac9cadd5c0e
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-07-28T20:06:30+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4cf40a11-c76e-44eb-80f8-c4aa33a60e3a # Partnerlink
            handle: null
            includeInCards: true
            instructions: null
            label: 'Bondgenoot URL'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b0324f09-951f-4082-96e3-c017287099de
            userCondition: null
            warning: null
            width: 25
        name: Content
        uid: 6d845169-a5fe-4a94-a473-9b7fd5803dbf
        userCondition: null
handle: matrixPartnerlinks
hasTitleField: true
icon: handshake-simple
name: 'Matrix Partnerlinks'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{partnerlink|striptags|slice(0, 250)}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
