color: null
description: null
fieldLayouts:
  a714dec4-e254-4c9b-8b54-3ad9895926e2:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-01T08:46:55+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: b4a68018-339f-43be-b93e-ba3d04ebb412
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-08-01T08:49:42+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c1c4a87b-7ed0-4bf8-b09a-8ced23b78cbe # Rich text
            handle: intro
            includeInCards: false
            instructions: null
            label: Intro
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: eaec9716-4a97-46fb-902d-8c8c7b50c4b4
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-08-01T08:49:42+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c1c4a87b-7ed0-4bf8-b09a-8ced23b78cbe # Rich text
            handle: body
            includeInCards: false
            instructions: null
            label: 'Body tekst'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 69950c1d-6a4b-4b38-ad94-ac6b47da8428
            userCondition: null
            warning: null
            width: 75
        name: Content
        uid: f2351855-43b5-49f5-990a-56fb34dc4439
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-01T08:49:42+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 12850798-946a-4531-a231-f9e868cf34e8 # SEO Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 25e0fdbe-533e-4dfc-a1a5-ff5a2d0ff734
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-08-01T08:49:42+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c4272228-e1b4-42b6-92df-560e599e3ba0 # SEO Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0a8b3b80-d594-43b5-a4cb-804e47d57660
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-08-01T08:49:42+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\LineBreak
            uid: 16dbac4c-8f39-4922-8bef-0944050307af
            userCondition: null
          -
            dateAdded: '2025-08-01T08:49:42+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ca05a040-7552-46ee-9e63-e43b76993591 # SEO Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 21418332-3bdf-4cc8-b108-289b872fadd1
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-08-01T08:49:42+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4e92aea7-75c3-4f7b-937d-2f0ebc589124 # SEO Tags
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9286c8cd-64a7-4b38-9af4-344a94c06a77
            userCondition: null
            warning: null
            width: 50
        name: SEO
        uid: 6a6d9164-0593-4d60-ab86-fb4c93220da7
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-01T08:52:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7a2b019e-db5b-4d0b-b9bd-e69504df603f # Embed
            handle: video
            includeInCards: false
            instructions: null
            label: 'Video embed'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6c1beab9-60c9-42b8-8942-8ae380715a12
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-08-01T08:52:51+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c1c4a87b-7ed0-4bf8-b09a-8ced23b78cbe # Rich text
            handle: videoText
            includeInCards: false
            instructions: null
            label: 'Tekst bij video'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 76acd15a-f578-41c9-843f-9fb5760e360e
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2025-08-04T11:23:33+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\LineBreak
            uid: 25f84992-8aff-402d-9ad3-2f3871a52be7
            userCondition: null
          -
            dateAdded: '2025-08-04T11:23:33+00:00'
            elementCondition: null
            heading: 'Video upload'
            type: craft\fieldlayoutelements\Heading
            uid: 59374995-236f-4261-86ae-109db753d78c
            userCondition: null
          -
            dateAdded: '2025-08-02T11:40:36+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ea15277b-7e0a-4d85-b0ad-e03bd8ad68d1 # Download
            handle: fileVideo
            includeInCards: false
            instructions: 'MP4 bestand'
            label: 'Upload video file'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d38608a3-88fc-44d7-8ba3-454aa4c0d18f
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-08-04T11:23:33+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d3781e8d-e07a-4cbe-beaf-73ccb0fc60b5 # Plain Text Multiline
            handle: videoScript
            includeInCards: false
            instructions: null
            label: 'Plaats hier het uitgeschreven videoscript'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 84b34d97-1329-475d-aabf-bd0cddcc9d7f
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-08-14T12:36:37+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\LineBreak
            uid: 9a73f79f-96d7-4bb3-abef-d37cd376af21
            userCondition: null
          -
            dateAdded: '2025-08-14T12:33:55+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f8e4f16b-1f73-48a6-95f3-14eb90a53351 # Button
            handle: shareInstagram
            includeInCards: false
            instructions: null
            label: 'Video op Instagram'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4fca6f8a-962e-4129-ac17-9363c29783ec
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-08-14T12:36:37+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f8e4f16b-1f73-48a6-95f3-14eb90a53351 # Button
            handle: shareFacebook
            includeInCards: false
            instructions: null
            label: 'Video op Facebook'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6493dba7-2a99-4d2e-a80a-749352da4835
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-08-14T12:36:37+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f8e4f16b-1f73-48a6-95f3-14eb90a53351 # Button
            handle: shareLinkedin
            includeInCards: false
            instructions: null
            label: 'Video op LinkedIn'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2fe1d432-5252-4ab6-87e4-efad4ae3426d
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-08-14T16:50:33+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\LineBreak
            uid: 00b78b31-8367-4cc3-95c3-4c094c9f084f
            userCondition: null
          -
            dateAdded: '2025-08-14T14:47:46+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: f8e4f16b-1f73-48a6-95f3-14eb90a53351 # Button
            handle: shareWhatsapp
            includeInCards: false
            instructions: null
            label: 'Link voor Whatsapp'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 93cc8edc-7426-4d40-af7f-6ba1b70bb25c
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-08-14T16:49:45+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d3781e8d-e07a-4cbe-beaf-73ccb0fc60b5 # Plain Text Multiline
            handle: messageText
            includeInCards: false
            instructions: null
            label: 'WhatsApp bericht tekst'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3a37c167-fe89-43d6-ad37-838ab61841e9
            userCondition: null
            warning: null
            width: 25
        name: 'Blok video'
        uid: 16cc5dae-c352-43e5-9a90-552056074870
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-21T10:41:14+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 17b994ad-10c2-454d-b160-9332d3c9c7c9 # Plain Text Single Line
            handle: toolkitTitle
            includeInCards: false
            instructions: null
            label: Titel
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 2af95212-c870-4239-876f-9c4250653c3a
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-08-01T08:53:52+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c1c4a87b-7ed0-4bf8-b09a-8ced23b78cbe # Rich text
            handle: toolkitText
            includeInCards: false
            instructions: null
            label: Tekst
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 843fc5f0-bdb3-4f6d-8fa2-f5a131e86297
            userCondition: null
            warning: null
            width: 75
        name: 'Blok Toolkit'
        uid: a1882d56-9f85-4592-ab3f-0efc0fe94c04
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-01T09:02:30+00:00'
            dismissible: false
            elementCondition: null
            style: tip
            tip: 'De tekst moet door Peter worden aangepast. Je kunt alleen de link aanpassen.'
            type: craft\fieldlayoutelements\Tip
            uid: 771aa886-dd4c-4942-8869-a313c73437f0
            userCondition: null
          -
            dateAdded: '2025-08-21T10:43:57+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 1541c9cc-8eac-456a-9dc1-fc556741c310 # External Link
            handle: demoLink
            includeInCards: false
            instructions: null
            label: 'Externe link'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 20ab2344-4c0c-41f1-bcd3-913fb5b000e1
            userCondition: null
            warning: null
            width: 100
        name: 'Blok Demo'
        uid: f7a9fb37-f971-4d73-b974-afdc89d1a67e
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-01T08:56:34+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 17b994ad-10c2-454d-b160-9332d3c9c7c9 # Plain Text Single Line
            handle: ctaOrgTitle
            includeInCards: false
            instructions: null
            label: 'Blok titel'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e4435471-5c37-4b6d-89af-200fc031a92b
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-08-01T08:56:34+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c1c4a87b-7ed0-4bf8-b09a-8ced23b78cbe # Rich text
            handle: ctaOrgText
            includeInCards: false
            instructions: null
            label: 'Blok bodytekst'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 579f9ec6-4c33-48a3-bfb6-cb751b26bfba
            userCondition: null
            warning: null
            width: 75
        name: 'CTA organisaties'
        uid: ebe93c09-0b68-46a0-a525-9fa5b90f4cb9
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-08-03T19:29:49+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 17b994ad-10c2-454d-b160-9332d3c9c7c9 # Plain Text Single Line
            handle: ctaMeedoenTitle
            includeInCards: false
            instructions: null
            label: 'Blok titel'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 838b5d2a-8666-47a6-a2f4-4cc6625662d9
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-08-03T19:29:49+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c1c4a87b-7ed0-4bf8-b09a-8ced23b78cbe # Rich text
            handle: ctaMeedoenText
            includeInCards: false
            instructions: null
            label: 'Blok bodytekst'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c3f79617-3cfd-4ff6-85a3-4ee032e71a70
            userCondition: null
            warning: null
            width: 75
        name: 'CTA Toolkit'
        uid: 662130e8-d95c-4353-bcf9-6e67ffa0f098
        userCondition: null
handle: meedoen
hasTitleField: true
icon: bullhorn
name: Meedoen
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
