color: null
description: null
fieldLayouts:
  60b197c2-ba31-4d11-abe3-024495cce195:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-29T12:31:09+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 17b994ad-10c2-454d-b160-9332d3c9c7c9 # Plain Text Single Line
            handle: preTitle
            includeInCards: false
            instructions: null
            label: Boventitel
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e7c3e16a-b00f-4d33-a1b9-ff79ca0c2742
            userCondition: null
            warning: null
            width: 50
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-29T12:26:01+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 92471e6f-4c96-4d39-9e7d-d5e9519cee76
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-29T12:30:24+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c1c4a87b-7ed0-4bf8-b09a-8ced23b78cbe # Rich text
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fc0dfb3b-093e-41f7-9a52-f5511cf6f483
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-29T12:30:24+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8a24d274-81ff-485b-a833-2bb7f51b19f4 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 490a0d95-78f9-4006-8dd5-0fe145e00ea9
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 65d5b937-5071-404b-99d1-a3060108512d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-29T12:30:24+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 12850798-946a-4531-a231-f9e868cf34e8 # SEO Title
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d32d9b76-260b-406e-9961-730acee31178
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-07-29T12:30:24+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c4272228-e1b4-42b6-92df-560e599e3ba0 # SEO Description
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6d7e03bd-1b77-4f74-b45a-4a9d09d5afec
            userCondition: null
            warning: null
            width: 75
          -
            dateAdded: '2025-07-29T12:30:24+00:00'
            elementCondition: null
            type: craft\fieldlayoutelements\LineBreak
            uid: ea73002e-1986-4fe6-80a3-cd49c5fe243a
            userCondition: null
          -
            dateAdded: '2025-07-29T12:30:24+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ca05a040-7552-46ee-9e63-e43b76993591 # SEO Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e8271198-84a3-450a-b951-1224f2f21607
            userCondition: null
            warning: null
            width: 25
          -
            dateAdded: '2025-07-29T12:30:24+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 4e92aea7-75c3-4f7b-937d-2f0ebc589124 # SEO Tags
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 43208ede-3209-4242-95c4-df9e82cc6b45
            userCondition: null
            warning: null
            width: 25
        name: SEO
        uid: b2e803e6-16de-4a81-958c-d0a701bf7c19
        userCondition: null
handle: nieuws
hasTitleField: true
icon: newspaper
name: Nieuws
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
