color: null
description: null
fieldLayouts:
  b99f464c-59ff-4e52-801f-c1e5a6e4f4c6:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-14T11:19:37+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 325f6f32-eb75-464c-b9d3-6f948691ea70
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-14T11:21:49+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: c1c4a87b-7ed0-4bf8-b09a-8ced23b78cbe # Rich text
            handle: bodyText
            includeInCards: false
            instructions: null
            label: Body
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5397a140-0bf9-457b-94a3-4261ddffa46b
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8b9522da-7d66-4d99-becb-e45a1ea8d194
        userCondition: null
handle: pages
hasTitleField: true
icon: file
name: Pages
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
