altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  bbe36655-8b9a-435a-915d-f50fed4220e4:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-08-02T11:35:35+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 91e5f89b-0704-402b-ac94-a70118b66869
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-08-02T11:39:04+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ea15277b-7e0a-4d85-b0ad-e03bd8ad68d1 # Download
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a1d77861-5e39-4416-92c1-efbc6e283198
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: f06f2c62-b2f3-49c9-9bc7-e565c381a6a1
        userCondition: null
fs: localStorage
handle: downloads
name: Downloads
sortOrder: 4
subpath: downloads
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
