altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  662db9eb-3b0b-43d9-8c19-0bd5d7812546:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-28T19:48:46+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 03d7e89f-a1c0-4c14-bed0-6e4647e6cdaf
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8e2a41e9-6c0c-43db-bc91-96c0930b967a
        userCondition: null
fs: localStorage
handle: embeds
name: Embeds
sortOrder: 2
subpath: embeds
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
