altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  36340d9a-cad8-4430-8d36-c39579f85561:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-28T19:20:18+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8a24d274-81ff-485b-a833-2bb7f51b19f4 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 43141fc6-c365-4ae7-9f89-85a70af53be7
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-28T19:16:03+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 23089c7b-9021-49f2-a1fb-50e3c580181d
            userCondition: null
            warning: null
            width: 100
          -
            attribute: alt
            class: null
            cols: null
            dateAdded: '2025-07-28T19:20:18+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            instructions: null
            label: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: true
            required: false
            rows: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AltField
            uid: 2ccb1a4c-2803-4fb4-b391-72be759b04a0
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1452794b-a3b5-4686-9148-c1d255d7384f
        userCondition: null
fs: localStorage
handle: images
name: Images
sortOrder: 1
subpath: images
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: images/transforms
