altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  89682309-612c-43fc-b246-71514ae5fd2c:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-07-28T20:21:09+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 7b57aa6d-4e04-4dac-8010-a4807abd184f
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-07-28T20:22:52+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 8a24d274-81ff-485b-a833-2bb7f51b19f4 # Image
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9e0edd88-3bfa-4e97-baa5-7e90424f9cee
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: df2f100e-a83c-4c76-b92b-e94e4957ce26
        userCondition: null
fs: localStorage
handle: partnerlogos
name: Partnerlogos
sortOrder: 3
subpath: partnerlogos
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: partnerlogos/transforms
