fieldLayouts:
  2a84b9cf-7682-4427-97ad-c5da60a68cb1:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-07-28T20:02:21+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 17b994ad-10c2-454d-b160-9332d3c9c7c9 # Plain Text Single Line
            handle: headerNieuwsbrief
            includeInCards: false
            instructions: null
            label: 'Header nieuwsbrief'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 75704252-bf2f-4a98-925c-61564b26670f
            userCondition: null
            warning: null
            width: 100
        name: Nieuwsbrief
        uid: 5c00b9b7-c478-4e84-be33-1c5e3bd36aaf
        userCondition: null
handle: socialMedia
name: 'Blijf op de hoogte'
sortOrder: 1
