defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 2fac30b3-8ffa-4d72-82bc-6b144ee5422c # Toolkit
handle: toolkit
maxAuthors: 1
name: Toolkit
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  7fd54027-fd83-4ca4-ac47-7ee712e38c14: # Stop de asielwetten
    enabledByDefault: true
    hasUrls: true
    template: toolkit/index.twig
    uriFormat: toolkit
type: single
